---
- name: Install and start HTTP service
  hosts: all
  become: true

  tasks:
    - name: Install Apache HTTP Server
      package:
        name: apache2
        state: present

    - name: Start Apache service
      service:
        name: apache2
        state: started

